### ISSUE TITLE
Second flag not rendering

### ISSUE THREAD

**Issue by fshubthunfischbaum** [eramsorgr-me/fshub-hooks2discord-tracker#10]
**Describe the bug**
Second Flag of the embed is not rendered by instead written out.

**To Reproduce**
1. Create new webhook with FsHub2Discord
2. Fly to destination and land
3. Look at your Discord Channel

**Expected behavior**
Second flag should be visible as emote

**Screenshots**
![image](https://github.com/eramsorgr-me/fshub-hooks2discord-tracker/assets/92665749/b5d704a3-6dc0-4346-85b2-e2035779496f)

**Additional context**
Only happening on landing

**Comment by alepouna** [comment]
thanks, I thought ive fixed that with the recent patches, thanks for the report I will look into it

**Comment by alepouna** [comment]
As I am moving repositories, please recreate this issue here: https://gitlab.com/fshub.tools/public-tracker/-/issues/new thank you :)
