### ISSUE TITLE
Option to remove lines with N/A

### ISSUE THREAD

**Issue by cowreth** [eramsorgr-me/fshub-hooks2discord-tracker#3]
**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
I'd love an option where fields with no information are not displayed in the embed. Most of the time, users are not submitting the plan, and so we got a lot of "lost space" for multiple N/A ;)

Thaaaaanks
:)

**Comment by eramsorgr** [comment]
I can "hide" the flight plan, thats not a big problem however for other values its going to be slightly more interesting to do. 
I will ask @FsHub reallyquickly to see how big the URL can be. Maybe you can add it as an option at the end of the webhook: 
`/?nona=1` and it will not show FP n/a :)

**Comment by eramsorgr** [comment]
It's possible! Now on the todo.

**Comment by eramsorgr** [comment]
Done by default on v0.58!
